### ISSUE TITLE
RuntimeError: 视频预拉取出错

### ISSUE THREAD

**Issue by ShuJun-Junical** [SocialSisterYi/CxKitty#11]
# RuntimeError: 视频预拉取出错

## 运行环境

 - 操作系统：Debian 11 bullseye
 - 内核版本：x86_64 Linux 5.10.0-11-amd64
 - Python版本：Python 3.10.8
 - Poetry版本：Poetry (version 1.3.1)

## 报错内容

```
RuntimeError: 视频预拉取出错
```

![报错截图](https://user-images.githubusercontent.com/39018081/208284365-5adf12b3-5d84-471a-a9a4-5d1db3f97645.png)

<details><summary>报错文本</summary>

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/lighthouse/RemoteWorking/CxKitty/cxapi/jobs/video.py:73 in pre_fetch                       │
│                                                                                                  │
│    70 │   │   resp.raise_for_status()                                                            │
│    71 │   │   html = BeautifulSoup(resp.text, 'lxml')                                            │
│    72 │   │   try:                                                                               │
│ ❱  73 │   │   │   if r := re.search(r'window\.AttachmentSetting *= *(.+?);', html.head.find('s   │
│    74 │   │   │   │   attachment = json.loads(r.group(1))                                        │
│    75 │   │   │   else:                                                                          │
│    76 │   │   │   │   raise ValueError                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/lighthouse/RemoteWorking/CxKitty/main.py:131 in <module>                                   │
│                                                                                                  │
│   128 │   │   classes = api.fetch_classes()  # 拉取该账号下所学的课程                            │
│   129 │   │   inp = dialog.select_class(console, classes)  # 进行选择课程                        │
│   130 │   │   chap = classes.fetch_chapters_by_index(int(inp))                                   │
│ ❱ 131 │   │   fuck_task_worker(chap)                                                             │
│   132 │   except Exception as err:                                                               │
│   133 │   │   console.print_exception(show_locals=False)                                         │
│   134 │   │   api.logger.error('-----*程序运行异常退出*-----', exc_info=True)                    │
│                                                                                                  │
│ /home/lighthouse/RemoteWorking/CxKitty/main.py:69 in fuck_task_worker                            │
│                                                                                                  │
│    66 │   │   │   │   continue                                                                   │
│    67 │   │   │   for task_point in chap.fetch_points_by_index(index):  # 获取当前章节的所有任   │
│    68 │   │   │   │   # 预拉取任务点数据                                                         │
│ ❱  69 │   │   │   │   prefetch_status = task_point.pre_fetch()                                   │
│    70 │   │   │   │   if not prefetch_status:                                                    │
│    71 │   │   │   │   │   del task_point                                                         │
│    72 │   │   │   │   │   continue                                                               │
│                                                                                                  │
│ /home/lighthouse/RemoteWorking/CxKitty/cxapi/jobs/video.py:89 in pre_fetch                       │
│                                                                                                  │
│    86 │   │   │   return False  # 非任务点视频不需要完成                                         │
│    87 │   │   except Exception:                                                                  │
│    88 │   │   │   self.logger.error('预拉取失败')                                                │
│ ❱  89 │   │   │   raise RuntimeError('视频预拉取出错')                                           │
│    90 │                                                                                          │
│    91 │   def fetch(self) -> bool:                                                               │
│    92 │   │   '拉取视频'                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: 视频预拉取出错
程序运行出现错误, 请截图保存并附上 log 文件在 issue 提交
```

</details>

## 错误日志

```
2022-12-18 14:08:21,193 [Chapters] INFO -> 获取章节任务节点卡片成功 共 1 个 [8.1:历年真题一(Id.657778397)]
2022-12-18 14:08:21,195 [Chapters] DEBUG -> (0) 解析卡片成功 共 3 个任务点
2022-12-18 14:08:21,195 [Chapters] DEBUG -> (0, 0) 视频任务点 schema: {'objectid': 'a11c45576b67c1ad70ebac4f936da27a', 'name': '2019-12-25-1历年真题一填空单选.avi', 'type': '.avi', 'size': 379664384, 'hsize': '362.08 MB', 'mid': '8266337055801577437367671', '_jobid': '1577437370044633', 'doublespeed': 1, 'retract': 'true'}
2022-12-18 14:08:21,195 [Chapters] DEBUG -> (0, 1) 视频任务点 schema: {'objectid': 'b08b0011303fc585228a5f78c9b13250', 'name': '2019-12-25-3历年真题一计算B.avi', 'type': '.avi', 'size': 520065536, 'hsize': '495.97 MB', 'mid': '11492115890911577437559470', '_jobid': '1577437561660449', 'doublespeed': 1}
2022-12-18 14:08:21,196 [Chapters] DEBUG -> (0, 2) 视频任务点 schema: {'objectid': 'ff885a3c7d5cef1d3c17a2fc3f9c76e6', 'name': '2019-12-25-2历年真题一计算A.avi', 'type': '.avi', 'size': 69211136, 'hsize': '66 MB', 'mid': '15727121474031577437410292', '_jobid': '157743741223550', 'doublespeed': 1}
2022-12-18 14:08:21,196 [Chapters] INFO -> 章节 任务节点解析成功 共 3 个 [8.1:历年真题一(Id.657778397)]
2022-12-18 14:08:21,250 [PointVideo] DEBUG -> attachment: {'hiddenConfig': False, 'attachments': [{'begins': 0, 'otherInfo': 'nodeId_657778397-cpi_264685886-rt_d-ds_1-ff_d-be_0_0-vt_1-v_6-enc_f8482df47669eeefc8867e6f2f8e1436&courseId=228640141', 'customType': 0, 'ends': 0, 'property': {'size': 379664384, 'hsize': '362.08 MB', 'retract': 'true', 'module': 'insertvideo', 'name': '2019-12-25-1历年真题一填空单选.avi', 'mid': '8266337055801577437367671', 'type': '.avi', 'doublespeed': 1, 'objectid': 'a11c45576b67c1ad70ebac4f936da27a', '_jobid': '1577437370044633'}, 'mid': '8266337055801577437367671', 'jumpTimePointList': [], 'type': 'video', 'aid': 1274104218, 'objectId': 'a11c45576b67c1ad70ebac4f936da27a'}, {'begins': 0, 'otherInfo': 'nodeId_657778397-cpi_264685886-rt_d-ds_1-ff_d-be_0_0-vt_1-v_6-enc_f8482df47669eeefc8867e6f2f8e1436&courseId=228640141', 'customType': 0, 'ends': 0, 'property': {'size': 520065536, 'hsize': '495.97 MB', 'module': 'insertvideo', 'name': '2019-12-25-3历年真题一计算B.avi', 'mid': '11492115890911577437559470', 'type': '.avi', 'doublespeed': 1, 'objectid': 'b08b0011303fc585228a5f78c9b13250', '_jobid': '1577437561660449'}, 'mid': '11492115890911577437559470', 'jumpTimePointList': [], 'type': 'video', 'aid': 1274104219, 'objectId': 'b08b0011303fc585228a5f78c9b13250'}, {'begins': 0, 'otherInfo': 'nodeId_657778397-cpi_264685886-rt_d-ds_1-ff_d-be_0_0-vt_1-v_6-enc_f8482df47669eeefc8867e6f2f8e1436&courseId=228640141', 'customType': 0, 'ends': 0, 'property': {'size': 69211136, 'hsize': '66 MB', 'module': 'insertvideo', 'name': '2019-12-25-2历年真题一计算A.avi', 'mid': '15727121474031577437410292', 'type': '.avi', 'doublespeed': 1, 'objectid': 'ff885a3c7d5cef1d3c17a2fc3f9c76e6', '_jobid': '157743741223550'}, 'mid': '15727121474031577437410292', 'jumpTimePointList': [], 'type': 'video', 'aid': 1274104220, 'objectId': 'ff885a3c7d5cef1d3c17a2fc3f9c76e6'}, {'begins': 0, 'otherInfo': 'nodeId_657778397-cpi_264685886', 'ends': 0, 'property': {'module': 'insertimage', 'objectid': '58a7296b1e34bc79591396d5acb36550'}, 'aid': 1274104221}, {'begins': 0, 'otherInfo': 'nodeId_657778397-cpi_264685886', 'ends': 0, 'property': {'module': 'insertimage', 'objectid': '49f9dca34c979716348408faaaa0c696'}, 'aid': 1274104222}, {'begins': 0, 'otherInfo': 'nodeId_657778397-cpi_264685886', 'ends': 0, 'property': {'module': 'insertimage', 'objectid': '255a6fbc3341652e9cfb282bef54283c'}, 'aid': 1274104223}, {'begins': 0, 'otherInfo': 'nodeId_657778397-cpi_264685886', 'ends': 0, 'property': {'module': 'insertimage', 'objectid': '3f28d62b72e334187b8e4b9cc82b20a1'}, 'aid': 1274104224}, {'begins': 0, 'otherInfo': 'nodeId_657778397-cpi_264685886', 'ends': 0, 'property': {'module': 'insertimage', 'objectid': '2d73ffe8bfff3becf9b641422f0aa176'}, 'aid': 1274104225}], 'coursename': '高等数学B—微积分(一)2022-2023上', 'defaults': {'fid': '7', 'ktoken': '948523e4f02bbead8afe497048a8fef8', 'mtEnc': '548163c6252309d2086531ffb3a3a3b6', 'playingCapture': 1, 'videoAutoPlay': 0, 'userid': '238341800', 'reportTimeInterval': 60, 'endCapture': 0, 'defenc': 'edd946f4c9b993903e6e3f4fbee849ed', 'cardid': 610689214, 'imageUrl': 'https://p.ananas.chaoxing.com/star3/origin/1e8e06d8884895a0065af6a603d38033.jpg', 'state': 0, 'cpi': 264685886, 'captureInterval': 10, 'playAginCapture': 0, 'startCapture': 1, 'isFiled': 0, 'ignoreVideoCtrl': 0, 'reportUrl': 'https://mooc1-api.chaoxing.com/multimedia/log/a/264685886', 'chapterCapture': 0, 'initdataUrl': 'https://mooc1-api.chaoxing.com/richvideo/initdatawithviewer', 'knowledgeid': 657778397, 'videoTopicCloud': 0, 'qnenc': '74c28c3083cbe081537560c22e6ae6db', 'clazzId': 63591612, 'chapterCollectionType': 0, 'lastmodifytime': 1671205888000, 'courseid': 228640141, 'subtitleUrl': 'https://mooc1-api.chaoxing.com/richvideo/subtitle', 'playingLoopCapture': 0}, 'mooc2': 0, 'knowledgename': '历年真题一', 'control': True, 'chapterVideoTranslate': 0, 'isErya': 2}
2022-12-18 14:08:21,250 [PointVideo] INFO -> 不存在任务已忽略
2022-12-18 14:08:21,327 [PointVideo] ERROR -> 预拉取失败
2022-12-18 14:08:21,416 [MainAPI] ERROR -> -----*程序运行异常退出*-----
Traceback (most recent call last):
  File "/home/lighthouse/RemoteWorking/CxKitty/cxapi/jobs/video.py", line 73, in pre_fetch
    if r := re.search(r'window\.AttachmentSetting *= *(.+?);', html.head.find('script', type='text/javascript').text):
AttributeError: 'NoneType' object has no attribute 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lighthouse/RemoteWorking/CxKitty/main.py", line 131, in <module>
    fuck_task_worker(chap)
  File "/home/lighthouse/RemoteWorking/CxKitty/main.py", line 69, in fuck_task_worker
    prefetch_status = task_point.pre_fetch()
  File "/home/lighthouse/RemoteWorking/CxKitty/cxapi/jobs/video.py", line 89, in pre_fetch
    raise RuntimeError('视频预拉取出错')
RuntimeError: 视频预拉取出错
```

全部日志如下：

[cxkitty_15533181757.log](https://github.com/SocialSisterYi/CxKitty/files/10253287/cxkitty_15533181757.log)

**Comment by SocialSisterYi** [comment]
请在文件`cxapi/jobs/video.py`的71行`html = BeautifulSoup(resp.text, 'lxml') `下方添加`print(html)`输出card页的html源码检查内嵌js代码是否存在对`window.AttachmentSetting`的赋值语句

**Comment by RigoLigoRLC** [comment]
我的一个课开始的部分章节没有开放，出现了相同的错误。页面源码为：
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"
name="viewport"/>
<title> 信息提示</title>
<link href="/css/tip.css?v=1.0.3" rel="stylesheet"/>
<script src="/static/js/domain.js" type="text/javascript"></script>
<script src="/js/phone/protocolChaoXing/CXJSBridge.js"></script>










</script>
</head>
<body>
<div class="ybox">
<p class="blankTips">章节未开放！</p>
</div>
</body>
</html>
```

**Comment by 2563411574** [comment]
> 为了刷课自己hack了一个能运行的，估计没什么参考价值
> 
> ```diff
> diff --git a/cxapi/jobs/video.py b/cxapi/jobs/video.py
> index fbc8675..75f0804 100644
> --- a/cxapi/jobs/video.py
> +++ b/cxapi/jobs/video.py
> @@ -86,6 +86,11 @@ class ChapterVideo:
>          resp.raise_for_status()
>          html = BeautifulSoup(resp.text, "lxml")
>          try:
> +            try:
> +                if 'blankTips' in html.p['class']:
> +                    return False
> +            except Exception:
> +                pass
>              if r := re.search(
>                  r"window\.AttachmentSetting *= *(.+?);",
>                  html.head.find("script", type="text/javascript").text,
> ```

大佬 这个要加在哪里呢
