### ISSUE TITLE
闪退报错提示：TypeError: 'NoneType' object is not iterable  已经正确配置题库了，并且在配置文件中开启了答题

### ISSUE THREAD

**Issue by 2563411574** [SocialSisterYi/CxKitty#110]
2024-01-04 13:00:54,008 [Main] ERROR -> 
-----*程序运行异常退出*-----
Traceback (most recent call last):
  File "main.py", line 363, in <module>
  File "main.py", line 198, in fuck_task_worker
  File "resolver\question.py", line 185, in __init__
  File "resolver\question.py", line 56, in load_searcher
TypeError: 'NoneType' object is not iterable

相关错误如图所示

<img width="1280" alt="2e0381cec07a9a436e1c73b9b629f48" src="https://github.com/SocialSisterYi/CxKitty/assets/42865393/086f9bb2-8fda-4c8b-bff5-8603fe6febf0">
<img width="1162" alt="6d6419fcf7b4ba4206e4add5546abd8" src="https://github.com/SocialSisterYi/CxKitty/assets/42865393/c362c3d4-cd16-474b-b822-d732f46a09a9">
<img width="1280" alt="8534de38fc2fb9fe211fdd75d92ea4e" src="https://github.com/SocialSisterYi/CxKitty/assets/42865393/3a63a57b-5f49-453a-a44c-c5ffca20edf4">

**Comment by SocialSisterYi** [comment]
该问题由于 config 文件不符合规定合适导致，请在`searcher`字段下使用 list 增加配置字段，而不是根节点下直接添加字段

**Comment by NonFelm** [comment]
你好哥，解决了吗。我的enncy题库也是这样的问题。明明还剩点数
