### ISSUE TITLE
发生异常: TypeError

### ISSUE THREAD

**Issue by NonFelm** [SocialSisterYi/CxKitty#129]
![屏幕截图 2024-03-21 185102](https://github.com/SocialSisterYi/CxKitty/assets/147258869/7449814e-a554-4a2a-a717-df1b8280c89b)
如图
D:\CodeGithub\CxKitty>C:/Users/SouthLine/AppData/Local/Programs/Python/Python310/python.exe d:/CodeGithub/CxKitty/CxKitty/main.py
d:\CodeGithub\CxKitty\CxKitty\**config.py:11: RuntimeWarning: Config file not found
  warnings.warn("Config file not found", RuntimeWarning)**
Traceback (most recent call last):
  File "d:\CodeGithub\CxKitty\CxKitty\main.py", line 15, in <module>
    import config
  File "d:\CodeGithub\CxKitty\CxKitty\config.py", line 16, in <module>
    EXPORT_PATH = Path(conf.get("export_path"))
  File "C:\Users\SouthLine\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 958, in __new__
    self = cls._from_parts(args)
  File "C:\Users\SouthLine\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 592, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\Users\SouthLine\AppData\Local\Programs\Python\Python310\lib\pathlib.py", line 576, in _parse_args
    a = os.fspath(a)
**TypeError: expected str, bytes or os.PathLike object, not NoneType**

**Comment by SocialSisterYi** [comment]
请检查 config.yml 是否存在，以及`export_path`字段是否有效
