### ISSUE TITLE
已看课程全部清零

### ISSUE THREAD

**Issue by DiyaDe** [SocialSisterYi/CxKitty#130]
使用服务器运行，服务器IP地址为香港地区
系统版本 ： Ubuntu 20.04.1 LTS (Focal Fossa) x86_64
python版本：Python 3.10.4
pip版本：24.0
未使用推荐的poetry管理，使用的是requirements.txt文件加pip安装库
安装库的版本如下
```python
requests==2.31.0
qrcode==7.4.2
rich==13.7.1
pycryptodome==3.20.0
lxml==5.1.0
pyyaml==6.0.1
jsonpath-python==1.0.6
beautifulsoup4==4.12.3
ddddocr==1.4.11
numpy==1.26.4
opencv-python==4.9.0.80
dataclasses-json==0.6.4
yarl==1.9.4
```
出现如下bug：
1. 已看课程全部清零
2. 如图 <img width="1145" alt="1711335798211" src="https://github.com/SocialSisterYi/CxKitty/assets/104015495/b3b8073b-01c0-4c9c-af69-1578cc651631">
3. 运行日志
```
2024-03-25 02:08:57,724 [Main] ERROR -> 
-----*程序运行异常退出*-----
Traceback (most recent call last):
  File "/www/wwwroot/docker/main.py", line 372, in <module>
    fuck_task_worker(task_obj)
  File "/www/wwwroot/docker/main.py", line 213, in fuck_task_worker
    resolver.execute()
  File "/www/wwwroot/docker/resolver/question.py", line 418, in execute
    result = self.exam_dto.final_submit()
  File "/www/wwwroot/docker/cxapi/task_point/work.py", line 320, in final_submit
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: https://mooc1-api.chaoxing.com/work/addStudentWorkNew?keyboardDisplayRequiresUserAction=1&_classId=96014524&courseid=242073585&token=a7dcc2bf27262898aef1275b6defb108&workAnswerId=52811690&workid=33543357&cpi%3A=211375093&jobid=work-7d20a473457d4f0ca3b7d3645c182fbe&knowledgeid=843985063&ua=app
```
4. 个人猜测是否是更新的检测机制，导致非大陆IP，或者异常时间段观看网课，导致的程序已看课程的清零，亦或者是其他检测机制

**Comment by guowang23333** [comment]
不用想就是ip原因，你可以clash挂一条国内ip即可

**Comment by DiyaDe** [comment]
> 不用想就是ip原因，你可以clash挂一条国内ip即可

好的，谢谢

**Comment by UPman24** [comment]
同样出现这个情况，IP在国内

**Comment by guowang23333** [comment]
> 同样出现这个情况，IP在国内

确定不是网络波动么。

**Comment by guowang23333** [comment]
> 同样出现这个情况，IP在国内
或者同时打开了多个程序

**Comment by UPman24** [comment]
> > 同样出现这个情况，IP在国内
> 
> 确定不是网络波动么。

不会是网络波动，程序是运行在服务器上的
