### ISSUE TITLE
易姐，可不可以选用多个题库？

### ISSUE THREAD

**Issue by cjuwen** [SocialSisterYi/CxKitty#15]
经常是一个题库有一个答案错误了，然后错误退出。

**Comment by cjuwen** [comment]
还有一个问题
![image](https://user-images.githubusercontent.com/20887192/209914553-1b6ac3b3-8f94-4707-8aae-cb19d4cf3e26.png)
找到答案了，但答案不是选项，是选项的内容，变成答案错误

**Comment by SocialSisterYi** [comment]
不一定是没有匹配到选项的情况，需要提供log文件才能检查问题

**Comment by cjuwen** [comment]
2022-12-29 14:54:47,837 [Chapters] INFO -> 获取章节任务节点卡片成功 共 0 个 [1:项目1 初识HTML5(Id.662912460)]
2022-12-29 14:54:47,837 [Chapters] INFO -> 章节 任务节点解析成功 共 0 个 [1:项目1 初识HTML5(Id.662912460)]
2022-12-29 14:54:47,885 [Chapters] INFO -> 获取章节任务节点卡片成功 共 1 个 [1.1:任务1.1 Web概述(Id.662912467)]
2022-12-29 14:54:47,886 [Chapters] WARNING -> (0) 卡片 iframe 不存在 {'knowledgeid': 662912467, 'description': '', 'id': 616065409, 'cardorder': 0, 'title': ''}
2022-12-29 14:54:47,886 [Chapters] INFO -> 章节 任务节点解析成功 共 0 个 [1.1:任务1.1 Web概述(Id.662912467)]
2022-12-29 14:54:47,886 [Chapters] INFO -> 忽略完成任务点 [1.1.1:任务1.1.1Web原理基础(Id.662912496)]
2022-12-29 14:54:47,986 [Chapters] INFO -> 忽略完成任务点 [1.1.2:任务1.1.2Web前端技术(Id.662912526)]
2022-12-29 14:54:48,087 [Chapters] INFO -> 忽略完成任务点 [1.1.3:章节测试(Id.662912576)]
2022-12-29 14:54:48,238 [Chapters] INFO -> 获取章节任务节点卡片成功 共 4 个 [1.2:任务1.2HTML5概述(Id.662912493)]
2022-12-29 14:54:48,238 [Chapters] WARNING -> (0) 卡片 iframe 不存在 {'knowledgeid': 662912493, 'description': '', 'id': 616065490, 'cardorder': 0, 'title': '微课视频'}
2022-12-29 14:54:48,238 [Chapters] WARNING -> (1) 卡片 iframe 不存在 {'knowledgeid': 662912493, 'description': '', 'id': 616065491, 'cardorder': 1, 'title': '学习资料'}
2022-12-29 14:54:48,238 [Chapters] WARNING -> (2) 卡片 iframe 不存在 {'knowledgeid': 662912493, 'description': '', 'id': 616065492, 'cardorder': 2, 'title': '自测试题'}
2022-12-29 14:54:48,238 [Chapters] WARNING -> (3) 卡片 iframe 不存在 {'knowledgeid': 662912493, 'description': '', 'id': 616065493, 'cardorder': 3, 'title': '主题讨论'}
2022-12-29 14:54:48,238 [Chapters] INFO -> 章节 任务节点解析成功 共 0 个 [1.2:任务1.2HTML5概述(Id.662912493)]
2022-12-29 14:54:48,238 [Chapters] INFO -> 忽略完成任务点 [1.2.1:任务1.2.1HTML5概述(Id.662912498)]
2022-12-29 14:54:48,339 [Chapters] INFO -> 忽略完成任务点 [1.2.2:任务1.2.2HTML5基本结构(Id.662912527)]
2022-12-29 14:54:48,439 [Chapters] INFO -> 忽略完成任务点 [1.2.3:任务1.2.3HTML5开发环境(Id.662912528)]
2022-12-29 14:54:48,589 [Chapters] INFO -> 获取章节任务节点卡片成功 共 1 个 [1.2.4:章节测试(Id.662912580)]
2022-12-29 14:54:48,590 [Chapters] DEBUG -> (0) 解析卡片成功 共 1 个任务点
2022-12-29 14:54:48,590 [Chapters] DEBUG -> (0, 0) 测验任务点 schema: {'workid': '93e1692bbcce44b1af281bbd0de4d938', 'title': 'HTML题库测试2', 'worktype': 'workA', 'mid': '6718396555921620899237061', '_jobid': 'work-93e1692bbcce44b1af281bbd0de4d938', 'jobid': 'work-93e1692bbcce44b1af281bbd0de4d938'}
2022-12-29 14:54:48,590 [Chapters] INFO -> 章节 任务节点解析成功 共 1 个 [1.2.4:章节测试(Id.662912580)]
2022-12-29 14:54:48,662 [PointExam] DEBUG -> attachment: {'hiddenConfig': False, 'attachments': [{'begins': 0, 'jobid': 'work-93e1692bbcce44b1af281bbd0de4d938', 'otherInfo': 'nodeId_662912580-cpi_233652721', 'ends': 0, 'property': {'jobid': 'work-93e1692bbcce44b1af281bbd0de4d938', 'module': 'work', 'worktype': 'workA', 'mid': '6718396555921620899237061', 'title': 'HTML题库测试2', 'workid': '93e1692bbcce44b1af281bbd0de4d938', '_jobid': 'work-93e1692bbcce44b1af281bbd0de4d938'}, 'mid': '6718396555921620899237061', 'enc': '8be75db298f664e0f6bba57b248d42ec', 'job': True, 'type': 'workid', 'aid': 1285983687}], 'coursename': 'HTML5网页编程', 'defaults': {'fid': '185272', 'ktoken': '41e1139d875643c71956198fba43e3d6', 'mtEnc': 'c713b2cd0b5d5d5e946f6576408b3905', 'playingCapture': 1, 'videoAutoPlay': 0, 'userid': '217532639', 'reportTimeInterval': 60, 'endCapture': 0, 'defenc': '2c931c18812e9720320df8d17614a906', 'cardid': 616065783, 'imageUrl': 'https://p.ananas.chaoxing.com/star3/origin/f6748a482e717b740074a8343b719b79.png', 'state': 0, 'cpi': 233652721, 'captureInterval': 10, 'playAginCapture': 0, 'startCapture': 1, 'isFiled': 0, 'ignoreVideoCtrl': 0, 'reportUrl': 'https://mooc1-api.chaoxing.com/multimedia/log/a/233652721', 'chapterCapture': 0, 'initdataUrl': 'https://mooc1-api.chaoxing.com/richvideo/initdatawithviewer', 'knowledgeid': 662912580, 'videoTopicCloud': 0, 'qnenc': '21a30353c24f444675567e796983d75f', 'clazzId': 64436312, 'chapterCollectionType': 0, 'lastmodifytime': 1668331567000, 'courseid': 228998037, 'subtitleUrl': 'https://mooc1-api.chaoxing.com/richvideo/subtitle', 'playingLoopCapture': 0}, 'mooc2': 0, 'knowledgename': '章节测试', 'control': True, 'chapterVideoTranslate': 0, 'isErya': 2}
2022-12-29 14:54:48,663 [PointExam] INFO -> 预拉取成功
2022-12-29 14:54:48,843 [PointExam] INFO -> 拉取成功
2022-12-29 14:54:48,864 [PointExam] DEBUG -> question schema: {'q_id': 402372224, 'value': '在HTML中,标签<i>的作用是( )', 'q_type': <QuestionType.单选题: 0>, 'answers': {'A': '文本的字体加粗', 'B': '文本的字体变细', 'C': '文本的字体加下划线', 'D': '文本的字体为斜体'}, 'answer': ''}
2022-12-29 14:54:48,865 [PointExam] DEBUG -> question schema: {'q_id': 402372225, 'value': '在HTML中，标签<pre>的作用是', 'q_type': <QuestionType.单选题: 0>, 'answers': {'A': '', 'B': '', 'C': '', 'D': ''}, 'answer': ''}
2022-12-29 14:54:48,867 [PointExam] DEBUG -> question schema: {'q_id': 402372226, 'value': '在HTML中，标签<pre>的作用是', 'q_type': <QuestionType.单选题: 0>, 'answers': {'A': '标题标签', 'B': '预排版标签', 'C': '转行标签', 'D': '文字效果标签'}, 'answer': ''}
2022-12-29 14:54:48,867 [PointExam] DEBUG -> question schema: {'q_id': 402372227, 'value': '在HTML中,标签<pre>的作用是( )', 'q_type': <QuestionType.单选题: 0>, 'answers': {'A': '标题标签', 'B': '预排版标签', 'C': '转行标签', 'D': '文字效果标签'}, 'answer': ''}
2022-12-29 14:54:48,868 [PointExam] DEBUG -> question schema: {'q_id': 402372228, 'value': '以下属于HTML中注释的语法的是( )', 'q_type': <QuestionType.单选题: 0>, 'answers': {'A': '', 'B': '/* <p>HTML</p> */', 'C': '<-- <p>HTML</p> -->', 'D': '// <p>HTML</p>'}, 'answer': ''}
2022-12-29 14:54:48,869 [PointExam] DEBUG -> question schema: {'q_id': 402372229, 'value': '关于HTML中的事件,说法正确的是( )', 'q_type': <QuestionType.多选题: 1>, 'answers': {'A': '当输入焦点转移到input输入框时,将触发对象的onfocus事件', 'B': '当输入焦点转移到input输入框时,将触发对象的onblur事件', 'C': '当输入焦点移出input输入框时,将触发对象的onfocus事件', 'D': '当输入焦点移出input输入框时,将触发对象的onblur事件'}, 'answer': ''}
2022-12-29 14:54:48,869 [PointExam] INFO -> 试题解析成功 共 6 道 [HTML题库测试1(J.work-93e1692bbcce44b1af281bbd0de4d938/W.93e1692bbcce44b1af281bbd0de4d938)]
2022-12-29 14:54:48,869 [PointExam] INFO -> 开始完成试题 [HTML题库测试1(J.work-93e1692bbcce44b1af281bbd0de4d938/W.93e1692bbcce44b1af281bbd0de4d938)]
2022-12-29 14:54:48,873 [PointExam] DEBUG -> 题库调用成功 req=在HTML中,标签<i>的作用是( ) rsp=[SearchResp(code=0, message=ok, searcher=<searcher.RestAPISearcher object at 0x7f5fa20abd90>, question=在HTML中,标签<i>的作用是( ), answer=文本字体为斜体)]
2022-12-29 14:54:48,873 [PointExam] DEBUG -> 开始填充题目 [在HTML中,标签<i>的作用是( )(Id.402372224)]
2022-12-29 14:54:48,874 [PointExam] DEBUG -> 单选题命中 D=文本的字体为斜体 [在HTML中,标签<i>的作用是( )(Id.402372224)]
2022-12-29 14:54:49,878 [PointExam] DEBUG -> 题库调用成功 req=在HTML中，标签<pre>的作用是 rsp=[SearchResp(code=0, message=ok, searcher=<searcher.RestAPISearcher object at 0x7f5fa20abd90>, question=在HTML中，标签<pre>的作用是, answer=预排版标记)]
2022-12-29 14:54:49,879 [PointExam] DEBUG -> 开始填充题目 [在HTML中，标签<pre>的作用是(Id.402372225)]
2022-12-29 14:54:49,879 [PointExam] WARNING -> 单选题填充失败 [在HTML中，标签<pre>的作用是(Id.402372225)]
2022-12-29 14:54:50,883 [PointExam] DEBUG -> 题库调用成功 req=在HTML中，标签<pre>的作用是 rsp=[SearchResp(code=0, message=ok, searcher=<searcher.RestAPISearcher object at 0x7f5fa20abd90>, question=在HTML中，标签<pre>的作用是, answer=预排版标记)]
2022-12-29 14:54:50,883 [PointExam] DEBUG -> 开始填充题目 [在HTML中，标签<pre>的作用是(Id.402372226)]
2022-12-29 14:54:50,884 [PointExam] WARNING -> 单选题填充失败 [在HTML中，标签<pre>的作用是(Id.402372226)]
2022-12-29 14:54:51,889 [PointExam] DEBUG -> 题库调用成功 req=在HTML中,标签<pre>的作用是( ) rsp=[SearchResp(code=0, message=ok, searcher=<searcher.RestAPISearcher object at 0x7f5fa20abd90>, question=在HTML中,标签<pre>的作用是( ), answer=预排版标记)]
2022-12-29 14:54:51,889 [PointExam] DEBUG -> 开始填充题目 [在HTML中,标签<pre>的作用是( )(Id.402372227)]
2022-12-29 14:54:51,889 [PointExam] WARNING -> 单选题填充失败 [在HTML中,标签<pre>的作用是( )(Id.402372227)]
2022-12-29 14:54:52,894 [PointExam] DEBUG -> 题库调用成功 req=以下属于HTML中注释的语法的是( ) rsp=[SearchResp(code=0, message=ok, searcher=<searcher.RestAPISearcher object at 0x7f5fa20abd90>, question=以下属于HTML中注释的语法的是( ), answer=＜!-- ＜p＞HTML＜/p＞ --＞)]
2022-12-29 14:54:52,894 [PointExam] DEBUG -> 开始填充题目 [以下属于HTML中注释的语法的是( )(Id.402372228)]
2022-12-29 14:54:52,894 [PointExam] WARNING -> 单选题填充失败 [以下属于HTML中注释的语法的是( )(Id.402372228)]
2022-12-29 14:54:53,899 [PointExam] DEBUG -> 题库调用成功 req=关于HTML中的事件,说法正确的是( ) rsp=[SearchResp(code=0, message=ok, searcher=<searcher.RestAPISearcher object at 0x7f5fa20abd90>, question=关于HTML中的事件,说法正确的是( ), answer=HTML 是网页的核心，是一种超文本标记的页面描述语言)]
2022-12-29 14:54:53,899 [PointExam] DEBUG -> 开始填充题目 [关于HTML中的事件,说法正确的是( )(Id.402372229)]
2022-12-29 14:54:53,900 [PointExam] WARNING -> 多选题填充失败 [关于HTML中的事件,说法正确的是( )(Id.402372229)]
2022-12-29 14:54:54,900 [PointExam] WARNING -> 试题未完成 [HTML题库测试1(J.work-93e1692bbcce44b1af281bbd0de4d938/W.93e1692bbcce44b1af281bbd0de4d938)]
2022-12-29 14:54:54,900 [PointExam] WARNING -> 共 5 题未完成
--------------------
1.	q(单选题/0): 在HTML中，标签<pre>的作用是 
	o: A= B= C= D=
	a: 预排版标记
2.	q(单选题/0): 在HTML中，标签<pre>的作用是 
	o: A=标题标签 B=预排版标签 C=转行标签 D=文字效果标签
	a: 预排版标记
3.	q(单选题/0): 在HTML中,标签<pre>的作用是( ) 
	o: A=标题标签 B=预排版标签 C=转行标签 D=文字效果标签
	a: 预排版标记
4.	q(单选题/0): 以下属于HTML中注释的语法的是( ) 
	o: A= B=/* <p>HTML</p> */ C=<-- <p>HTML</p> --> D=// <p>HTML</p>
	a: ＜!-- ＜p＞HTML＜/p＞ --＞
5.	q(多选题/1): 关于HTML中的事件,说法正确的是( ) 
	o: A=当输入焦点转移到input输入框时,将触发对象的onfocus事件 B=当输入焦点转移到input输入框时,将触发对象的onblur事件 C=当输入焦点移出input输入框时,将触发对象的onfocus事件 D=当输入焦点移出input输入框时,将触发对象的onblur事件
	a: HTML 是网页的核心，是一种超文本标记的页面描述语言
--------------------
2022-12-29 14:55:14,970 [Chapters] INFO -> 任务点状态已更新
2022-12-29 14:55:15,017 [Chapters] INFO -> 获取章节任务节点卡片成功 共 0 个 [2:项目2 HTML5常用元素和属性(Id.662912461)]
2022-12-29 14:55:15,017 [Chapters] INFO -> 章节 任务节点解析成功 共 0 个 [2:项目2 HTML5常用元素和属性(Id.662912461)]
2022-12-29 14:55:15,065 [Chapters] INFO -> 获取章节任务节点卡片成功 共 1 个 [2.1:任务2.1HTML5常用标签(Id.662912468)]
2022-12-29 14:55:15,066 [Chapters] DEBUG -> (0) 解析卡片成功 共 1 个任务点
2022-12-29 14:55:15,066 [Chapters] DEBUG -> (0, 0) 视频任务点 schema: {'objectid': '7d804f647dfa0a550778a3a3d8d81401', 'name': '2.1.3图像标签超链接标签.mp4', 'size': 797839890, 'hsize': '760.88 MB', 'type': '.mp4', 'mid': '13437358160871618476794460', '_jobid': '1618476794717993', 'jobid': '1618476794717993', 'doublespeed': 1}
2022-12-29 14:55:15,066 [Chapters] INFO -> 章节 任务节点解析成功 共 1 个 [2.1:任务2.1HTML5常用标签(Id.662912468)]
2022-12-29 14:55:15,112 [PointVideo] ERROR -> 预拉取失败
2022-12-29 14:55:15,223 [MainAPI] ERROR -> -----*程序运行异常退出*-----
Traceback (most recent call last):
  File "/root/CxKitty/cxapi/jobs/video.py", line 76, in pre_fetch
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/CxKitty/main.py", line 133, in <module>
    fuck_task_worker(chapter)
  File "/root/CxKitty/main.py", line 73, in fuck_task_worker
    prefetch_status = task_point.pre_fetch()
  File "/root/CxKitty/cxapi/jobs/video.py", line 89, in pre_fetch
    raise RuntimeError('视频预拉取出错')
RuntimeError: 视频预拉取出错

**Comment by guowang23333** [comment]
这个是匹配率太低了，建议直接删掉api的exam里109行最后的>=0.9可以降低重复率或者改小数值都可以缓解，视频拉取出错是因为多视频章节我的建议是不管他，直接去video文件里删掉95行，直接关闭跳出让他一直执行下去，虽然预拉取失败了但还是会上报预拉取的任务点
