### ISSUE TITLE
KeyError: 'description'

### ISSUE THREAD

**Issue by traigh** [SocialSisterYi/CxKitty#19]
![image](https://user-images.githubusercontent.com/122506233/212057363-8b5399eb-315b-4968-b784-93f2f5b1c91e.png)
2023-01-12 19:25:09,233 [MainAPI] INFO -> 账号会话验证成功 
2023-01-12 19:25:09,233 [MainAPI] INFO -> -----*任务开始执行*-----
2023-01-12 19:25:09,374 [MainAPI] INFO -> 课程列表拉取成功 共 56 个
2023-01-12 19:25:12,874 [Classes] INFO -> 获取课程 章节列表成功 共 220 个 [大学国文（上）(Cou.232482133/Cla.71724353)]
2023-01-12 19:25:12,905 [Chapters] INFO -> 任务点状态已更新
2023-01-12 19:25:12,952 [Chapters] INFO -> 获取章节任务节点卡片成功 共 0 个 [1:总论(Id.512142648)]
2023-01-12 19:25:12,952 [Chapters] INFO -> 章节 任务节点解析成功 共 0 个 [1:总论(Id.512142648)]
2023-01-12 19:25:12,952 [Chapters] INFO -> 忽略完成任务点 [1.1:总论(Id.512142685)]
2023-01-12 19:25:13,061 [Chapters] INFO -> 忽略完成任务点 [1.2:诗经概述(Id.512142734)]
2023-01-12 19:25:13,170 [Chapters] INFO -> 忽略完成任务点 [1.3:孔子编纂说及非孔子编纂说(Id.512142823)]
2023-01-12 19:25:13,280 [Chapters] INFO -> 忽略完成任务点 [1.4:采诗说(Id.512142824)]
2023-01-12 19:25:13,389 [Chapters] INFO -> 忽略完成任务点 [1.5:诗经的内容、艺术特色及传播(Id.512142825)]
2023-01-12 19:25:13,499 [Chapters] INFO -> 忽略完成任务点 [1.6:章节测验(Id.512142828)]
2023-01-12 19:25:13,639 [Chapters] INFO -> 获取章节任务节点卡片成功 共 0 个 [2:诗经(Id.512142649)]
2023-01-12 19:25:13,639 [Chapters] INFO -> 章节 任务节点解析成功 共 0 个 [2:诗经(Id.512142649)]
2023-01-12 19:25:13,639 [Chapters] INFO -> 忽略完成任务点 [2.1:卫风•伯兮(Id.512142682)]
2023-01-12 19:25:13,749 [Chapters] INFO -> 忽略完成任务点 [2.2:王风•黍离(Id.512142712)]
2023-01-12 19:25:13,858 [Chapters] INFO -> 忽略完成任务点 [2.3:《黍离》赏析(Id.512142826)]
2023-01-12 19:25:13,967 [Chapters] INFO -> 忽略完成任务点 [2.4:“黍离麦秀”的文化现象(Id.512142827)]
2023-01-12 19:25:14,077 [Chapters] INFO -> 忽略完成任务点 [2.5:章节测验(Id.512142829)]
2023-01-12 19:25:14,217 [Chapters] INFO -> 获取章节任务节点卡片成功 共 1 个 [3:屈原(Id.512142650)]
2023-01-12 19:25:14,342 [MainAPI] ERROR -> -----*程序运行异常退出*-----
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\CxKitty-main\main.py", line 129, in <module>
    fuck_task_worker(chapter)
  File "C:\Users\Administrator\Desktop\CxKitty-main\main.py", line 66, in fuck_task_worker
    for task_point in chap.fetch_points_by_index(index):  # 获取当前章节的所有任务点, 并遍历
  File "C:\Users\Administrator\Desktop\CxKitty-main\cxapi\chapters.py", line 168, in fetch_points_by_index
    if card["description"] == "":
KeyError: 'description'
易姐,这门课运行到这个点就会崩,别的课试了下不会

**Comment by SocialSisterYi** [comment]
该 bug 已修复 https://github.com/SocialSisterYi/CxKitty/commit/3a708c5a3f29707e402bb7c844f04d054e9ebaab
问题是章节中含有不存在任务点的card，故字段`description`为空或不存在，且两种情况都有可能出现，这里应使用`not card.get("description")`而不是`card["description"] == ""`进行判定
