### ISSUE TITLE
怎么搞个api对接呀

### ISSUE THREAD

**Issue by XXXXBully** [SocialSisterYi/CxKitty#21]
答题姬有api吗，对接网站的，同步进度

**Comment by guowang23333** [comment]
写一个request请求就好了

**Comment by SocialSisterYi** [comment]
后期会加入这个红能，目前计划用MQTT协议上报进度，同时也计划接入 邮件 / 钉钉机器人 / tg机器人 / server酱 / gotify 等推送服务，进行完成及异常退出提醒

**Comment by XXXXBully** [comment]
Traceback (most recent call last):
  File "resolver\searcher\json.py", line 20, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'questions.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 277, in <module>
  File "main.py", line 118, in fuck_task_worker
  File "resolver\question.py", line 185, in __init__
  File "resolver\question.py", line 66, in load_searcher
  File "resolver\searcher\json.py", line 23, in __init__
RuntimeError: JSON 题库文件无效, 请检查配置

易姐，这个我已经配置了题库的token呀，为啥还会这样

**Comment by kitUIN** [comment]
不存在文件questions.json
你在配置文件里把本地文件题库关了就好
https://github.com/SocialSisterYi/CxKitty/blob/main/config.yml#L65

**Comment by XXXXBully** [comment]
> 不存在文件questions.json 你在配置文件里把本地文件题库关了就好 https://github.com/SocialSisterYi/CxKitty/blob/main/config.yml#L65

可以请教一下怎么关吗
![1693145817581](https://github.com/SocialSisterYi/CxKitty/assets/99703693/ad717a55-bef8-4856-b086-e1d805f5ced3)

**Comment by kitUIN** [comment]
至少得有一个搜索器,不用就注释掉

**Comment by XXXXBully** [comment]
> 
谢谢我会了，哥你知道怎么可以和彩虹网这种线上商城同步进度吗

**Comment by SocialSisterYi** [comment]
> > 
> 
> 谢谢我会了，哥你知道怎么可以和彩虹网这种线上商城同步进度吗

具体我也不知道，但计划下一步做 WebHook+MQTT+gotify+邮件 聚合推送服务，有可能对你的需求有帮助

**Comment by XXXXBully** [comment]
> 

好的谢谢啦我研究一下，想把这个项目好好做起来，是个很好的项目

**Comment by XXXXBully** [comment]
哥，如果对接其他题库呢，是否可以匹配



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月28日(周一) 凌晨2:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 怎么搞个api对接呀 (Issue #21)




    
谢谢我会了，哥你知道怎么可以和彩虹网这种线上商城同步进度吗
  
具体我也不知道，但计划下一步做 WebHook+MQTT+gotify+邮件 聚合推送服务，有可能对你的需求有帮助

**Comment by SocialSisterYi** [comment]
> 哥，如果对接其他题库呢，是否可以匹配
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月28日(周一) 凌晨2:26 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [SocialSisterYi/CxKitty] 怎么搞个api对接呀 (Issue #21) 谢谢我会了，哥你知道怎么可以和彩虹网这种线上商城同步进度吗 具体我也不知道，但计划下一步做 WebHook+MQTT+gotify+邮件 聚合推送服务，有可能对你的需求有帮助 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这个 Issue 中讨论的是状态上报 API/推送服务 对接，与题库无关

**Comment by cyxnzb** [comment]
个人建议的话可以前后端打通之后直接打包发布docker镜像方便管理，没有前端的话确实有点。。抽象，不过问题不大现在，还是可以进行无人值守的

**Comment by XXXXBully** [comment]
是可以的我也有想过，只不过有点麻烦不想弄



---原始邮件---
发件人: "YueXin ***@***.***&gt;
发送时间: 2023年10月10日(周二) 中午1:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SocialSisterYi/CxKitty] 怎么搞个api对接呀 (Issue #21)




 
个人建议的话可以前后端打通之后直接打包发布docker镜像方便管理，没有前端的话确实有点。。抽象，不过问题不大现在，还是可以进行无人值守的

**Comment by SocialSisterYi** [comment]
> 个人建议的话可以前后端打通之后直接打包发布docker镜像方便管理，没有前端的话确实有点。。抽象，不过问题不大现在，还是可以进行无人值守的

这个项目既不属于前端也不属于后端，它属于 worker，后面做 args 传参和 webhook 等等机制后，就可以对接管理后端

后端负责调度及监测各 worker 的状态，前端负责登录账号 选择课程 配置参数，并查看任务状态，但该前端并不直接与本项目通讯

**Comment by QBK2010** [comment]
![Snipaste_2023-10-25_03-11-18](https://github.com/SocialSisterYi/CxKitty/assets/75165193/c36a084c-96a6-4e4a-8dbe-6840aba80512)
![Snipaste_2023-10-25_03-12-08](https://github.com/SocialSisterYi/CxKitty/assets/75165193/44837542-50f0-4fa5-9a62-1856d9b685c3)
为什么无法运行？token已填写。

**Comment by NonFelm** [comment]
> ![Snipaste_2023-10-25_03-11-18](https://private-user-images.githubusercontent.com/75165193/277778482-c36a084c-96a6-4e4a-8dbe-6840aba80512.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1ODMyMDQsIm5iZiI6MTcxMTU4MjkwNCwicGF0aCI6Ii83NTE2NTE5My8yNzc3Nzg0ODItYzM2YTA4NGMtOTZhNi00ZTRhLThkYmUtNjg0MGFiYTgwNTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDIzNDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM2ZGE4OTRkMDQ2YWRlMDFkMGE5MThkZDBmNGYxMDBiYWUzNjIxZDU4Mzk0OTU1ZDNiZThiOWNhNDQ1MWMwOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hh5nNFGwcZ7WuxuvID9pEzC2BQWP7z_p4DzgTSqMhTU) ![Snipaste_2023-10-25_03-12-08](https://private-user-images.githubusercontent.com/75165193/277778489-44837542-50f0-4fa5-9a62-1856d9b685c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1ODMyMDQsIm5iZiI6MTcxMTU4MjkwNCwicGF0aCI6Ii83NTE2NTE5My8yNzc3Nzg0ODktNDQ4Mzc1NDItNTBmMC00ZmE1LTlhNjItMTg1NmQ5YjY4NWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDIzNDE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1YmM1YTRjNGRiMzk5OGVjMDMzZjA5MGFlMTRhMDllMzE3MWNiMmIyOWQ4YTliMThmNWNlODQwNzMzNTZiYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.McWOhzQRzZ7zHD84Ax3SrvciKenRJTQKhgRe7UQI0Zg) 为什么无法运行？token已填写。

同问
