### ISSUE TITLE
RuntimeError: 视频预拉取出错

### ISSUE THREAD

**Issue by TOL0VE** [SocialSisterYi/CxKitty#24]
![1111111](https://user-images.githubusercontent.com/38149298/224544923-66f9e3e9-1f27-4fb4-9152-b1b7aa63461d.jpg)

**Comment by TOL0VE** [comment]
--------------------
2023-03-12 18:05:47,737 [Chapters] INFO -> 任务点状态已更新
2023-03-12 18:05:47,771 [Chapters] INFO -> 获取章节任务节点卡片成功 共 1 个 [1.2:国家安全(Id.483139789)]
2023-03-12 18:05:47,771 [Chapters] DEBUG -> (0) 解析卡片成功 共 0 个任务点
2023-03-12 18:05:47,772 [Chapters] INFO -> 章节 任务节点解析成功 共 0 个 [1.2:国家安全(Id.483139789)]
2023-03-12 18:05:47,806 [Chapters] INFO -> 获取章节任务节点卡片成功 共 2 个 [1.2.1:习近平总书记提出总体国家安全观(Id.483139811)]
2023-03-12 18:05:47,807 [Chapters] DEBUG -> (0) 解析卡片成功 共 1 个任务点
2023-03-12 18:05:47,808 [Chapters] DEBUG -> (0, 0) 视频任务点 schema: {'objectid': '63aeb2e7fa31d614342fcf518fa3172f', 'name': '1-1-1.mp4', 'size': 383453306, 'hsize': '365.69 MB', 'type': '.mp4', 'mid': '9059498531411567041948372', '_jobid': '1566781452657894', 'jobid': '1566781452657894', 'fastforward': 'true', 'switchwindow': 'true', 'doublespeed': 1}
2023-03-12 18:05:47,808 [Chapters] DEBUG -> (1) 解析卡片成功 共 1 个任务点
2023-03-12 18:05:47,808 [Chapters] DEBUG -> (1, 0) 测验任务点 schema: {'workid': 'fc04604844d84a2e9eda7161c83e78d5', 'title': '习近平总书记提出总体国家安全观', 'worktype': 'workA', 'mid': '7771774477621567131853683', '_jobid': 'work-fc04604844d84a2e9eda7161c83e78d5', 'jobid': 'work-fc04604844d84a2e9eda7161c83e78d5'}
2023-03-12 18:05:47,808 [Chapters] INFO -> 章节 任务节点解析成功 共 2 个 [1.2.1:习近平总书记提出总体国家安全观(Id.483139811)]
2023-03-12 18:05:47,844 [PointVideo] ERROR -> 预拉取失败
2023-03-12 18:05:47,879 [PointExam] ERROR -> 预拉取失败
2023-03-12 18:05:48,089 [MainAPI] ERROR -> -----*程序运行异常退出*-----
Traceback (most recent call last):
  File "/home/lighthouse/CxKitty/cxapi/jobs/exam.py", line 150, in pre_fetch
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lighthouse/CxKitty/main.py", line 129, in <module>
    fuck_task_worker(chapter)
  File "/home/lighthouse/CxKitty/main.py", line 68, in fuck_task_worker
    prefetch_status = task_point.pre_fetch()
  File "/home/lighthouse/CxKitty/cxapi/jobs/exam.py", line 171, in pre_fetch
    raise RuntimeError("试题预拉取出错")
RuntimeError: 试题预拉取出错

**Comment by TOL0VE** [comment]
根据#9下的一个回复

> 可以选择删掉cxapi/jobs/video.py的89行直接跳过预拉取失败，这个办法并不能解决拉取出错的问题，但是可以直接跳过预拉取出错的视频，属于是一个关闭保险丝的操作了，但是经过实测，预拉取失败并不影响之后的正常拉去视频

注释掉了抛出异常。
可能是这个操作导致的RuntimeError: 试题预拉取出错

**Comment by TOL0VE** [comment]
等等发更详细issue

**Comment by TOL0VE** [comment]
![1111111](https://user-images.githubusercontent.com/38149298/224644343-0a386724-8e81-4312-a9ac-9e1cbebba226.png)
这种情况时会跳过这个任务节点进入任务点，视频预拉取出错

**Comment by TOL0VE** [comment]
![1111111](https://user-images.githubusercontent.com/38149298/224688698-2ff2b439-52c8-44e9-9da7-d17d28496717.png)
同样的，如果是纯文章任务点，默认没有任务点，但是不访问这个文章的话不给过

**Comment by TOL0VE** [comment]
![QQ截图20230313221956](https://user-images.githubusercontent.com/38149298/224729111-b4b19d68-d1a1-4c5d-a382-fe4b347b18b1.jpg)
测试发现，只要发出这个请求就可以触发观看记录
![QQ截图20230313222132](https://user-images.githubusercontent.com/38149298/224729446-8dd8e433-cad5-4709-8e71-9d175b14e05b.jpg)
不过我是在PC上测试出这个，直接写入佬的代码还不能正常运行

**Comment by TOL0VE** [comment]
chapters.py 239行添加如下代码
`        if len(point_objs) == 0:
            resp = self.session.get(
                "https://mooc1-api.chaoxing.com/job/submitstudy",
                params={
                    "node": params['id'],
                    "userid":self.acc.puid,
                    "clazzid":self.clazzid ,
                    "courseid": self.courseid,
                    "view":params["view"],
                    "token":params["token"],
                    "_time":params["_time"],
                    "inf_enc": calc_infenc(params)
                },
            )
`
即可解决
![QQ截图20230315130930](https://user-images.githubusercontent.com/38149298/225212752-4cb774a5-6d47-494a-af5c-1c15961183ed.jpg)

**Comment by 2563411574** [comment]
哥 这个问题又出现了 按照这个方法添加代码没用嘞
![微信截图_20230411004800](https://user-images.githubusercontent.com/42865393/230949798-8312bcbd-e045-48fd-8881-b846bec8370f.png)

**Comment by TOL0VE** [comment]
> 哥 这个问题又出现了 按照这个方法添加代码没用嘞 ![微信截图_20230411004800](https://user-images.githubusercontent.com/42865393/230949798-8312bcbd-e045-48fd-8881-b846bec8370f.png)

不清楚你的情况是什么样的，你可以试试在学习通怎么操作之后能让程序继续正常运行，看看是不是和我的情况一样
