### ISSUE TITLE
上报时出错

### ISSUE THREAD

**Issue by RF-Tar-Railt** [SocialSisterYi/CxKitty#27]
```
2023-03-28 19:21:21,876 [PointVideo] DEBUG -> 上报 resp: {'isPassed': False, 'videoTimeLimit': False, 'hasJobLimit': False}
2023-03-28 19:21:21,876 [PointVideo] INFO -> 播放上报成功 580/925
2023-03-28 19:22:42,424 [MainAPI] ERROR -> -----*程序运行异常退出*-----
Traceback (most recent call last):
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\TR\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\TR\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TR\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\urllib3\connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\TR\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1374, in getresponse
    response.begin()
  File "C:\Users\TR\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\TR\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Download\Projects\CxKitty\main.py", line 129, in <module>
    fuck_task_worker(chapter)
  File "D:\Download\Projects\CxKitty\main.py", line 87, in fuck_task_worker
    task_point.playing(lay_main, config.VIDEO["speed"], config.VIDEO["report_rate"])
  File "D:\Download\Projects\CxKitty\cxapi\jobs\video.py", line 196, in playing
    report_result = self.__play_report(playing_time)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\cxapi\jobs\video.py", line 138, in __play_report
    resp = self.session.get(
           ^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Download\Projects\CxKitty\.venv\Lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

```

**Comment by SocialSisterYi** [comment]
这个问题系学习通后端的风控机制，频繁请求接口似乎会使后端 RST 当前的 TCP 连接，需要为请求加入 Retry 处理

**Comment by SocialSisterYi** [comment]
#35
