### ISSUE TITLE
出现以下报错：RuntimeError: 视频预拉取出错 以下是log日志文件

### ISSUE THREAD

**Issue by 2563411574** [SocialSisterYi/CxKitty#29]
2023-04-10 23:52:29,915 [PointVideo] ERROR -> 预拉取失败
2023-04-10 23:52:29,956 [MainAPI] ERROR -> -----*程序运行异常退出*-----
Traceback (most recent call last):
  File "cxapi\jobs\video.py", line 95, in pre_fetch
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 129, in <module>
  File "main.py", line 68, in fuck_task_worker
  File "cxapi\jobs\video.py", line 117, in pre_fetch
RuntimeError: 视频预拉取出错

**Comment by ggsimida-cw** [comment]
> 2023-04-10 23:52:29,915 [PointVideo] ERROR -> 预测失败 2023-04-10 23:52:29,956 [MainAPI] ERROR -> -----_程序运行异常退出_----- 回源（最近调用最后）： 文件“cxapi\jobs\video.py”，第95行，在pre_fetch ValueError中
> 
> 在处理上描述异常的过程中，又出现了一个异常：
> 
> 追踪（最近调用最后）： 文件“main.py”，第129行，在 文件“main.py”，第68行，在fuck_task_worker 文件“cxapi\jobs\video.py”，第117行，在pre_fetch RuntimeError ：视频预拉取消错误
兄弟，现在好像连课程获取都失败了

**Comment by SocialSisterYi** [comment]
#9
