### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by FT1142558190** [SocialSisterYi/CxKitty#49]
我的流程pycharm新建项目地址是https://github.com/SocialSisterYi/CxKitty
然后新建本届3.10的解释器pip install -i https://pypi.tuna.tsinghua.edu.cn/simple -v Poetry==1.5.1
然后install poetry出现下面错误

我的办法是看pyproject.toml和poetry.lock这个看看我还少什么 不然肯定跑不起来

CalledProcessError

  Command '['F:\\code\\CxKitty\\venv\\Scripts\\python.exe', '-m', 'pip', 'uninstall', 'charset-normalizer', '-y']' returned non-zero exit status 2.

  at ~\AppData\Local\Programs\Python\Python310\lib\subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│
       528│

The following error occurred when trying to handle this error:

  EnvCommandError

  Command ['F:\\code\\CxKitty\\venv\\Scripts\\python.exe', '-m', 'pip', 'uninstall', 'charset-normalizer', '-y'] errored with the following return code 2

  Output:
  Found existing installation: charset-normalizer 3.2.0
  Uninstalling charset-normalizer-3.2.0:
    Successfully uninstalled charset-normalizer-3.2.0
  ERROR: Exception:
  Traceback (most recent call last):
    File "F:\code\CxKitty\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
      status = run_func(*args)
    File "F:\code\CxKitty\venv\lib\site-packages\pip\_internal\commands\uninstall.py", line 103, in run
      uninstall_pathset.commit()
    File "F:\code\CxKitty\venv\lib\site-packages\pip\_internal\req\req_uninstall.py", line 424, in commit
      self._moved_paths.commit()
    File "F:\code\CxKitty\venv\lib\site-packages\pip\_internal\req\req_uninstall.py", line 277, in commit
      save_dir.cleanup()
    File "F:\code\CxKitty\venv\lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
      rmtree(self._path)
    File "F:\code\CxKitty\venv\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 328, in wrapped_f
      return self(f, *args, **kw)
    File "F:\code\CxKitty\venv\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 408, in __call__
      do = self.iter(retry_state=retry_state)

**Comment by FT1142558190** [comment]
我成功了 哈哈

**Comment by SocialSisterYi** [comment]
建议不要使用 Pycharm 启动项目，直接使用 poetry 进行依赖的构建和运行项目
