### ISSUE TITLE
RuntimeError: 视频预拉取出错

### ISSUE THREAD

**Issue by smallwhitedesu1** [SocialSisterYi/CxKitty#9]
> 2022-12-16 17:29:17,890 [MainAPI] INFO -> -----*任务开始执行*-----
2022-12-16 17:29:19,410 [MainAPI] INFO -> 课程列表拉取成功 共 38 个
2022-12-16 17:29:32,937 [Classes] INFO -> 获取课程 章节列表成功 共 67 个 [美术鉴赏(Cou.210599244/Cla.63236432)]
2022-12-16 17:29:33,048 [Chapters] INFO -> 任务点状态已更新
2022-12-16 17:29:35,488 [Chapters] INFO -> 获取章节任务节点卡片成功 共 0 个 [1:美术鉴赏(Id.283986394)]
2022-12-16 17:29:35,488 [Chapters] INFO -> 章节 任务节点解析成功 共 0 个 [1:美术鉴赏(Id.283986394)]
2022-12-16 17:29:40,169 [Chapters] INFO -> 获取章节任务节点卡片成功 共 3 个 [1.1:美术作品和艺术哲学(Id.283986397)]
2022-12-16 17:29:40,172 [Chapters] DEBUG -> (0) 解析卡片成功 共 0 个任务点
2022-12-16 17:29:40,173 [Chapters] DEBUG -> (1) 解析卡片成功 共 1 个任务点
2022-12-16 17:29:40,173 [Chapters] DEBUG -> (1, 0) 视频任务点 schema: {'objectid': '53a80cd1a3103c3a4ed90b5e', 'name': 'TS127A60277A1.mp4', 'size': 187172901, 'hsize': '178.5 MB', 'type': '.mp4', 'mid': '523990373441404114462982', '_jobid': 1404114463260, 'fastforward': 'true', 'switchwindow': 'true', 'jobid': 1404114463260, 'retract': 'true'}
2022-12-16 17:29:40,174 [Chapters] DEBUG -> (2) 解析卡片成功 共 1 个任务点
2022-12-16 17:29:40,174 [Chapters] DEBUG -> (2, 0) 测验任务点 schema: {'workid': 'd5ea0aed5ecf4c6287247bd3b83a9906', 'title': '美术作品和艺术哲学', 'worktype': 'workA', 'mid': '11011725886731533366345488', '_jobid': 'work-d5ea0aed5ecf4c6287247bd3b83a9906', 'jobid': 'work-d5ea0aed5ecf4c6287247bd3b83a9906'}
2022-12-16 17:29:40,174 [Chapters] INFO -> 章节 任务节点解析成功 共 2 个 [1.1:美术作品和艺术哲学(Id.283986397)]
2022-12-16 17:29:49,648 [PointVideo] ERROR -> 预拉取失败
2022-12-16 17:29:49,882 [MainAPI] ERROR -> -----*程序运行异常退出*-----
Traceback (most recent call last):
  File "d:\网课\CxKitty\cxapi\jobs\video.py", line 76, in pre_fetch
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\网课\CxKitty\main.py", line 131, in <module>
    fuck_task_worker(chap)
  File "d:\网课\CxKitty\main.py", line 69, in fuck_task_worker
    prefetch_status = task_point.pre_fetch()
  File "d:\网课\CxKitty\cxapi\jobs\video.py", line 89, in pre_fetch
    raise RuntimeError('视频预拉取出错')
RuntimeError: 视频预拉取出错
![QQ图片20221216174244](https://user-images.githubusercontent.com/103363926/208070125-4dbc33fc-e6ef-4ab1-87e6-807f3fb44ad0.png)

**Comment by guowang23333** [comment]
可以选择删掉cxapi/jobs/video.py的89行直接跳过预拉取失败，这个办法并不能解决拉取出错的问题，但是可以直接跳过预拉取出错的视频，属于是一个关闭保险丝的操作了，但是经过实测，预拉取失败并不影响之后的正常拉去视频

**Comment by smallwhitedesu1** [comment]
感谢~

guowang23333 ***@***.***> 于2022年12月20日周二 21:01写道：

**Comment by wanghurui** [comment]
在闯关模式下，上一个题目在题库中未搜索到答案，自动进入下一课程章节时，会出现视频预拉取出错。
```
请输入欲完成的课程 (序号/名称/id), 输入q退出：0
╭───────────────────────────────────────────────────────────────────────────────────────────────────────╮╭─────────────────────── 《军事理论》章节列表 ───────────────────────╮
│ 试题《12.20》已结束, 课间等待14/15s                                                                   ││    12.13:毛泽东军事思想的历史地位与现实意义...    ...任务点2/2     │
│                                                                                                       ││    12.14:邓小平新时期军队建设思想的形成...    ...任务点2/2         │
│                                                                                                       ││    12.15:邓小平新时期军队建设思想的主要内容（上）...               │
│                                                                                                       ││ ...任务点2/2                                                       │
│                                                                                                       ││    12.16:邓小平新时期军队建设思想的主要内容（下）...               │
│                                                                                                       ││ ...任务点2/2                                                       │
│                                                                                                       ││    12.17:邓小平新时期军队建设思想的历史地位和实践意义...           │
│                                                                                                       ││ ...任务点2/2                                                       │
│                                                                                                       ││    12.18:江泽民国防和军队建设思想的科学含义...    ...任务点2/2     │
│                                                                                                       ││    12.19:江泽民国防和军队建设思想产生的时代背景...    ...任务点2/2 │
│                                                                                                       ││    12.20:江泽民国防和军队建设思想的主要内容...    ...任务点1/2     │
│                                                                                                       ││ ❱  12.21:江泽民国防和军队建设思想的地位与作用...    ...任务点0/0   │
│                                                                                                       ││    12.22:胡锦涛关于国防和军队建设重要论述（上）...    ...任务点0/0 │
│                                                                                                       ││    12.23:胡锦涛关于国防和军队建设重要论述（下）...    ...任务点0/0 │
│                                                                                                       ││    12.24:胡锦涛关于国防和军队建设重要论述的地位与作用...           │
│                                                                                                       ││ ...任务点0/0                                                       │
│                                                                                                       ││    12.25:习近平强军思想的核心内容    ...任务点0/0                  │
│                                                                                                       ││    12.26:习近平强军思想在国防和军队建设中的指导地位与...           │
│                                                                                                       ││ ...任务点0/0                                                       │
│                                                                                                       ││  13:战争概述    ...任务点0/0                                       │
│                                                                                                       ││    13.1:战争的内涵与特点    ...任务点0/0                           │
│                                                                                                       ││                                                                    │
│                                                                                                       ││                                                                    │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────╯╰────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/whr0622/CxKitty/cxapi/jobs/video.py:95 in pre_fetch                                        │
│                                                                                                  │
│    92 │   │   │   ):                                                                             │
│    93 │   │   │   │   attachment = json.loads(r.group(1))                                        │
│    94 │   │   │   else:                                                                          │
│ ❱  95 │   │   │   │   raise ValueError                                                           │
│    96 │   │   │   self.logger.debug(f"attachment: {attachment}")                                 │
│    97 │   │   │   self.fid = attachment["defaults"]["fid"]                                       │
│    98 │   │   │   # 定位资源objectid                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/whr0622/CxKitty/main.py:129 in <module>                                                    │
│                                                                                                  │
│   126 │   │   classes = api.fetch_classes()  # 拉取该账号下所学的课程                            │
│   127 │   │   course_seq = dialog.select_class(console, classes)  # 进行课程选择                 │
│   128 │   │   for chapter in course_seq:  # 迭代返回课程章节                                     │
│ ❱ 129 │   │   │   fuck_task_worker(chapter)                                                      │
│   130 │   except Exception as err:                                                               │
│   131 │   │   console.print_exception(show_locals=False)                                         │
│   132 │   │   api.logger.error("-----*程序运行异常退出*-----", exc_info=True)                    │
│                                                                                                  │
│ /home/whr0622/CxKitty/main.py:68 in fuck_task_worker                                             │
│                                                                                                  │
│    65 │   │   │   │   continue                                                                   │
│    66 │   │   │   for task_point in chap.fetch_points_by_index(index):  # 获取当前章节的所有任   │
│    67 │   │   │   │   # 预拉取任务点数据                                                         │
│ ❱  68 │   │   │   │   prefetch_status = task_point.pre_fetch()                                   │
│    69 │   │   │   │   if not prefetch_status:                                                    │
│    70 │   │   │   │   │   del task_point                                                         │
│    71 │   │   │   │   │   continue                                                               │
│                                                                                                  │
│ /home/whr0622/CxKitty/cxapi/jobs/video.py:117 in pre_fetch                                       │
│                                                                                                  │
│   114 │   │   │   return False                                                                   │
│   115 │   │   except Exception:                                                                  │
│   116 │   │   │   self.logger.error("预拉取失败")                                                │
│ ❱ 117 │   │   │   raise RuntimeError("视频预拉取出错")                                           │
│   118 │                                                                                          │
│   119 │   def fetch(self) -> bool:                                                               │
│   120 │   │   "拉取视频"                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: 视频预拉取出错
程序运行出现错误, 请截图保存并附上 log 文件在 issue 提交
whr0622@debian:~/CxKitty$

```

![image](https://user-images.githubusercontent.com/30315826/214467944-ecc7d1c3-2821-4a31-9f04-11a1afc0dd4b.png)

**Comment by TOL0VE** [comment]
> 可以选择删掉cxapi/jobs/video.py的89行直接跳过预拉取失败，这个办法并不能解决拉取出错的问题，但是可以直接跳过预拉取出错的视频，属于是一个关闭保险丝的操作了，但是经过实测，预拉取失败并不影响之后的正常拉去视频

好像会导致后面的测验点拉去试题失败

**Comment by SocialSisterYi** [comment]
问题很可能为接口风控导致，现在增加了打码支持
