### ISSUE TITLE
提示TypeError: 'NoneType' object is not iterable 报错后闪退

### ISSUE THREAD

**Issue by 2563411574** [SocialSisterYi/CxKitty#96]
2023-12-10 12:12:52,611 [Main] ERROR -> 
-----*程序运行异常退出*-----
Traceback (most recent call last):
  File "main.py", line 363, in <module>
  File "main.py", line 198, in fuck_task_worker
  File "resolver\question.py", line 185, in __init__
  File "resolver\question.py", line 56, in load_searcher
TypeError: 'NoneType' object is not iterable

**Comment by SocialSisterYi** [comment]
请在 config.yml 中至少添加一个 Seacher（搜索器），如果不使用答题功能，请将`work`下的`enable`字段设为`false`
